<?php

namespace App;

/**
 * Eloquent class to describe the actor table.
 *
 * automatically generated by ModelGenerator.php
 */
class Actor extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'actor';

    public $primaryKey = 'actor_id';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = ['first_name', 'last_name', 'last_update'];

    public function getDates()
    {
        return ['last_update'];
    }
}
