<?php

namespace App;

/**
 * Eloquent class to describe the address table.
 *
 * automatically generated by ModelGenerator.php
 */
class Address extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'address';

    public $primaryKey = '';

    public $incrementing = false;

    protected $fillable = ['address_id', 'address', 'address2', 'district', 'city_id', 'postal_code', 'phone'];
}
