<?php

namespace App;

/**
 * Eloquent class to describe the city table.
 *
 * automatically generated by ModelGenerator.php
 */
class City extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'city';

    public $primaryKey = '';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = ['city_id', 'city', 'country_id'];
}
