<?php

namespace App;

/**
 * Eloquent class to describe the customer table.
 *
 * automatically generated by ModelGenerator.php
 */
class Customer extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'customer';

    public $primaryKey = '';

    public $incrementing = false;

    protected $fillable = ['customer_id', 'store_id', 'first_name', 'last_name', 'email', 'address_id', 'active'];
}
