<?php

namespace App;

/**
 * Eloquent class to describe the film_category table.
 *
 * automatically generated by ModelGenerator.php
 */
class FilmCategory extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'film_category';

    public $primaryKey = '';

    public $incrementing = false;

    protected $fillable = ['film_id', 'category_id'];
}
