<?php

namespace App;

/**
 * Eloquent class to describe the film table.
 *
 * automatically generated by ModelGenerator.php
 */
class Film extends \Illuminate\Database\Eloquent\Model
{
    const RATING_G = 'G';
    const RATING_PG = 'PG';
    const RATING_PG-13 = 'PG-13';
    const RATING_R = 'R';
    const RATING_NC-17 = 'NC-17';

    protected $table = 'film';

    public $primaryKey = '';

    public $incrementing = false;

    protected $fillable = ['film_id', 'title', 'description', 'release_year', 'language_id', 'original_language_id',
        'rental_duration', 'rental_rate', 'length', 'replacement_cost', 'rating', 'special_features'];

    public function getDates()
    {
        return ['release_year'];
    }
}
