<?php

namespace App;

/**
 * Eloquent class to describe the film_text table.
 *
 * automatically generated by ModelGenerator.php
 */
class FilmText extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'film_text';

    public $primaryKey = '';

    public $incrementing = false;

    protected $fillable = ['film_id', 'title', 'description'];
}
