<?php

namespace App;

/**
 * Eloquent class to describe the inventory table.
 *
 * automatically generated by ModelGenerator.php
 */
class Inventory extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'inventory';

    public $primaryKey = '';

    public $incrementing = false;

    protected $fillable = ['inventory_id', 'film_id', 'store_id'];
}
