<?php

namespace App;

/**
 * Eloquent class to describe the language table.
 *
 * automatically generated by ModelGenerator.php
 */
class Language extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'language';

    public $primaryKey = '';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = ['language_id', 'name'];
}
