<?php

namespace App;

/**
 * Eloquent class to describe the password_reset_tokens table.
 *
 * automatically generated by ModelGenerator.php
 */
class PasswordResetTokens extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'password_reset_tokens';

    public $primaryKey = 'email';

    public $incrementing = false;

    protected $fillable = ['token'];
}
