<?php

namespace App;

/**
 * Eloquent class to describe the rental table.
 *
 * automatically generated by ModelGenerator.php
 */
class Rental extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'rental';

    public $primaryKey = '';

    public $incrementing = false;

    protected $fillable = ['rental_id', 'rental_date', 'inventory_id', 'customer_id', 'return_date', 'staff_id'];

    public function getDates()
    {
        return ['rental_date', 'return_date'];
    }
}
