<?php

namespace App;

/**
 * Eloquent class to describe the staff table.
 *
 * automatically generated by ModelGenerator.php
 */
class Staff extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'staff';

    public $primaryKey = '';

    public $incrementing = false;

    protected $fillable = ['staff_id', 'first_name', 'last_name', 'address_id', 'picture', 'email', 'store_id',
        'active', 'username', 'password'];
}
