<?php

namespace App;

/**
 * Eloquent class to describe the store table.
 *
 * automatically generated by ModelGenerator.php
 */
class Store extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'store';

    public $primaryKey = '';

    public $incrementing = false;

    protected $fillable = ['store_id', 'manager_staff_id', 'address_id'];
}
