<?php

namespace App;

/**
 * Eloquent class to describe the users table.
 *
 * automatically generated by ModelGenerator.php
 */
class Users extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'users';

    protected $fillable = ['name', 'email', 'password'];
}
